"""Shared helpers for ARC Skill workflow entry scripts."""

import sys


# Importing workflow helpers must not write generated bytecode into a checked-out
# or installed Skill tree.
sys.dont_write_bytecode = True
